INPUT_FILE = "urls.csv"
OUTPUT_DIR = "output"
TRANSCRIPT_OUTPUT_DIR = "transcripts"
SUMMARY_FILENAME = "summary.csv"

DOWNLOAD_AUDIO = True
TEST_MODE = True
MAX_URLS = 1

TRANSCRIPTION_MODEL = "tiny"
TRANSCRIPTION_DEVICE = "cpu"
TRANSCRIPTION_COMPUTE_TYPE = "int8"
