INPUT_FILE = "urls.csv"

OUTPUT_DIR = "output"
TRANSCRIPT_OUTPUT_DIR = "transcripts"
ANALYSIS_OUTPUT_DIR = "analysis"

SUMMARY_FILENAME = "summary.csv"

TEST_MODE = True
MAX_URLS = 1
DOWNLOAD_AUDIO = True

DEFAULT_CHUNK_SIZE = 12000

ANTHROPIC_MODEL = "claude-sonnet-4-5"
ANTHROPIC_MAX_TOKENS = 2000

TRANSCRIPTION_MODEL = "tiny"
TRANSCRIPTION_DEVICE = "cpu"
TRANSCRIPTION_COMPUTE_TYPE = "int8"